apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-postgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-017a91f59838dd637
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-redis
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-017a91f59838dd637
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-rabbitmq
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-017a91f59838dd637
