apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-redis
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-017a91f59838dd637::fsap-0723fdf0c546b3478
    volumeAttributes: 
      path: "/redis"
